### ISSUE TITLE
photo dates input

### ISSUE THREAD

**Issue by pmcelhany** [pmcelhany/dng_juv_size_2019#1]
@dmperez89 @krovinski
fix the crabID column of the [photo date file](https://github.com/pmcelhany/dng_juv_size_2019/blob/master/data/dng_juv_photo_dates_2019.csv) so that it only includes valid crab IDs.

**Comment by dmperez89** [comment]
@pmcelhany @KROVINSKI
I took a look at these and sent an email with an updated csv (it wouldn't let me attach here, for some reason).

**Comment by dmperez89** [comment]
Added new fileCreationDates_clean.csv file into data folder.

**Comment by pmcelhany** [comment]
Data look OK now
