### ISSUE TITLE
photographers

### ISSUE THREAD

**Issue by pmcelhany** [pmcelhany/dng_juv_size_2019#2]
@dmperez89 @krovinski
Do we have data on who took the photographs of the live juveniles?

**Comment by dmperez89** [comment]
@pmcelhany @KROVINSKI
no, we didn't keep track of who took photos. The best we could do is look at the google drive and see who it was last modified by, or take a look at the hard copy of the data sheets to see if we can glean anything from handwriting/notes. But even that would be conjecture.

**Comment by pmcelhany** [comment]
OK, we will consider this missing information.
